kind:Pod
apiVersion: v1 
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: Devops
    - name: student
      value: "Charan Kandukuri"
    - name: duration
      value: "120HRS"