kind: Pod
apiVersion: v1 
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
     # Soft Limit
      requests:
        memory: "68Mi"
        cpu: "100m"
     # Hard Limit
      limits:
        memory: "128Mi"
        cpu: "150m"