kind: Service
apiVersion: v1 
metadata:
  name: nginx
spec:
  selector:              # Lables are used as selectors 
    porject: expense
    component: backend
    environment: dev
    version: "1.0.0"
    ports:
    - protocol: TCP
      port: 80           # Service port
      targetPort: 80     # target container port (9376)

---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    porject: expense
    component: backend
    environment: dev
    version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx
