
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:              # Lables are used as selectors 
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
  ports:
    - protocol: TCP
      port: 80           # Service port
      targetPort: 80     # target container port (9376)


---

apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
spec:
  containers:
    - name: nginx
      image: nginx
